fix: Remove unused conversion functions interfering with other tests (#3820)
Remove unused conversion functions as they interfere with other tests
like:
```
2025/06/27 09:58:45 [DEBUG] Returning cached provider configuration context
    resource_function_javascript_acceptance_test.go:144: Step 2/3 error running import: ImportStateVerify attributes not equivalent. Difference is shown below. The - symbol indicates attributes missing after import.
        
          map[string]string{
        - 	"show_output.0.created_on": "2025-06-27T09:58:43.904Z",
        + 	"show_output.0.created_on": "2025-06-27T02:58:43.904-07:00",
          }
2025/06/27 09:58:46 [DEBUG] Returning cached provider configuration result
2025/06/27 09:58:46 [DEBUG] Returning cached provider configuration context
2025/06/27 09:58:46 [DEBUG] Returning cached provider configuration result
2025/06/27 09:58:46 [DEBUG] Returning cached provider configuration context
    2_check_destroy_test.go:48: found resource snowflake_function_javascript in state
    2_check_destroy_test.go:64: resource snowflake_function_javascript ("acc_test_db_AT_36CEA41069FF3DE45DA2D010E2EE2CEEF6EED569"."acc_test_sc_AT_36CEA41069FF3DE45DA2D010E2EE2CEEF6EED569"."NOFXEZAT_36CEA41069FF3DE45DA2D010E2EE2CEEF6EED569"(VARIANT)) was dropped successfully in Snowflake
--- FAIL: TestAcc_FunctionJavascript_InlineFull (3.14s)
```
or
```
2025/06/27 11:06:14 [DEBUG] Returning cached provider configuration context
    resource_notification_integration_acceptance_test.go:124: Step 3/3 error running import: ImportStateVerify attributes not equivalent. Difference is shown below. The - symbol indicates attributes missing after import.
        
          map[string]string{
          	"created_on": strings.Join({
          		"2025-06-27 ",
        - 		"11:06:11.972 +0000 UTC",
        + 		"04:06:11.972 -0700 PDT",
          	}, ""),
          }
2025/06/27 11:06:14 [DEBUG] Returning cached provider configuration result
2025/06/27 11:06:14 [DEBUG] Returning cached provider configuration context
2025/06/27 11:06:14 [DEBUG] Returning cached provider configuration result
2025/06/27 11:06:14 [DEBUG] Returning cached provider configuration context
    2_check_destroy_test.go:48: found resource snowflake_notification_integration in state
    2_check_destroy_test.go:64: resource snowflake_notification_integration ("OXQTFVAT_C80A56B0C290672942DA606932AAD9A058972942") was dropped successfully in Snowflake
--- FAIL: TestAcc_NotificationIntegration_PushAmazon (3.66s)
```