chore: Implement PoC for managing warehouse using terraform plugin framework (#3888)
Implement PoC for handling warehouse in Terraform Plugin Framework based
on the existing SDKv2 implementation

#### Main differences to SDKv2 implementation
- no support for `show_output` and `parameters`; private state
marshalling used instead
- parameters are no longer computed (due to earlier tests for olg logic)
- no support for identifier suppression
- `IgnoreChangeToCurrentSnowflakeValueInShow` couldn't be supported
(method left for reference with annotation to create a functional test
for this)
- Import state has the full reading logic
- Read after create/update is separated from the normal read (due to
different types and private state being in internal package)
- no current implementation for `handleExternalChangesToObjectInShow` -
to be discussed
- `setStateToValuesFromConfig` was completely omitted and it seems it's
not needed

#### Changes
- Configure the framework PoC provider
(`pkg/testacc/10_plugin_framework_poc_provider_configure_test.go`)
  - duplicate caching logic from the existing SDKv2 tests
  - handle only a subset of attributes (leave list of unsupported ones)
- skip handling `skip_toml_file_permission_verification` and
`use_legacy_toml_file`
  - skip handling `preview_features_enabled`
  - export `getDriverConfigFromTOML` to reuse its logic
  - export `getPrivateKey` to reuse its logic
- Add `FromString` method to `WarehouseType`, `WarehouseSize`, and
`ScalingPolicy` enums\
- Export method from testfunctional (`StringEnumAttributeCreate`,
`BooleanAttributeCreate`, `Int64AttributeCreate`,
`StringAttributeCreate`)
- Add missing methods to testfunctional, without tests
(`StringEnumAttributeUpdate`,
`StringEnumAttributeUpdateSetDefaultInsteadOfUnset`,
`StringEnumAttributeUpdateSetOnly`, `BooleanAttributeUpdate`,
`BooleanAttributeUpdateSetDefaultInsteadOfUnset`,
`Int64AttributeUpdate`, `Int64AttributeUpdateSetDefaultInsteadOfUnset`,
`IdAttributeCreate`, `StringAttributeUpdate`, `IdAttributeUpdate`)
- Change signature of some helpers to return error
- Add custom plan modifer for replace when removed from config
(`RequiresReplaceIfRemovedFromConfig`); without dedicated functional
tests
- Extract `fully_qualified_name` as embeddable struct and provide a
common schema (to be decided later what logic is needed)
- Extract `SnowflakeClientEmbeddable` to easily gain access to Snowflake
Client in resources

#### Testing
There are two acceptance test files:
1. `pkg/testacc/plugin_framework_poc_warehouse_acceptance_test.go` just
checking the basic setup
2.
`pkg/testacc/plugin_framework_poc_warehouse_sdkv2_copy_acceptance_test.go`
which is a copy of the existing SDKv2 implementation acceptance tests
with the following modifications:
   - Migration tests were not copied.
   - Experimental tests were not copied.
   - Models used are the same, but with the resource type replaced.
   - Assertions used are the same, but with the resource type replaced.
- Assertions using `r.IntDefaultString` or `r.BooleanDefault` were
replaced (as such defaults are not needed in the Terraform Plugin
Framework).
- Parameter assertions were adjusted due to changed behavior (parameter
values are not in state when the config does not contain them). Default
parameter assertions can't be used because of this.
- `WarehouseShowOutput` assertions were removed or replaced with
Snowflake object assertions (as PoC was done using private state and not
`show_output`).
- `WarehouseResourceParameters` assertions were removed or replaced with
Snowflake parameters assertions (as PoC was done using private state and
not `parameters`).
   - Default extensions were not used as they don't match.
- Expectations for tests utilizing
IgnoreChangeToCurrentSnowflakeValueInShow were adjusted.
- Computed expectations for parameters were adjusted (`ExpectComputed`
-> `ExpectChange`).
- Exchanged some old assertions with new ones for easier Snowflake
checks.
- `IgnoreAfterCreation` is not implemented, so assertions for
`initially_suspended` were adjusted.
- Identifier suppression is not implemented, so adjusted steps with
resource monitor.
- `TestCheckResourceAttr` checks were replaced with
`TestCheckNoResourceAttr` for values absent in config (as plugin
framework handles null differently).
   - Validation tests regex assertions were adjusted.
- Test verifying `initially_suspended` is skipped till the
`IgnoreAfterCreate` is implemented.
- Additional step to tackle (similar test will be added to the existing
resource):
```
        001425 (22023): SQL compilation error:
        invalid property combination 'RESOURCE_CONSTRAINT'='MEMORY_16X' and
        'WAREHOUSE_SIZE'='X-Small'
```

#### Other changes
- in the original warehouse:
- change `sdk.ObjectParameterMaxConcurrencyLevel` ->
`sdk.WarehouseParameterMaxConcurrencyLevel`
  - remove duplication for handling parameters in update

#### For later research/changes:
- Create follow up tasks for the `mux-PR` TODOs
- Handle `CheckDestroy` in PoC plugin framework resources (the protected
enum is used now)
- Decide how we can handle `IgnoreAfterCreation`
- Handle suppression for identifiers (custom types?)
- Add functional tests for added helper methods (create and update)
- Add functional tests for `RequiresReplaceIfRemovedFromConfig`
- Follow up on fully qualified name logic
- Add `show_output` and `parameters` (preferably conditionally)
- Extract modifier for id and fully_qualified_name (like we had
`ComputedIfAnyAttributeChanged`)
- Add functional test documenting that
`IgnoreChangeToCurrentSnowflakeValueInShow` cannot be achieved that way.
- Discuss if we want to handle imports differently
- Discuss if we want to merge read logic
- Discuss how we want to implement `handleExternalChangesToObjectInShow`
equivalent